### ISSUE TITLE
[Design] Feed UI 구현

### ISSUE THREAD

**Issue by Naknakk** [DeveloperAcademy-POSTECH/2024-MC3-M6-LavenderPhanHani#6]
## 🛠 Issue

- Feed UI를 구현합니다.

## 📝 To-do

- [ ] Feed 카드 UI
- [ ] Feed 확대버전 UI
- [ ] Feed 모아보기 버전 UI
