### ISSUE TITLE
[Practice] 호세연습

### ISSUE THREAD

**Issue by interstellaar** [DeveloperAcademy-POSTECH/2024-MC3-M6-LavenderPhanHani#9]
## 🛠 Issue

브랜치를 만드는 연습)(7/25)
## 📝 To-do

- [x] 이슈 생성
- [x] 브랜치 생성
- [x] 각자 변경사항 만들기
- [x] 커밋올리기
- [x] pr올리기
- [x] 코드 리뷰 해보기
- [x] 충돌 해결 후 머지
